### PR TITLE
Add basic card images

### PR DESCRIPTION
**Pull request by andburn**
Ok, so here's what I have. I'm pretty ignorant regards React and TypeScript (seperate or together), so open to all suggestions on how to better structure this or do it differently. I also slightly butchered your CSS, wasn't able to keep the nice overlap you had on the cards, while trying to keep the images in proportion. So suggestion there too maybe?

### CODE REVIEW

**Comment by jleclanche** [comment]
What's portrait.jpg?

**Comment by andburn** [comment]
Its just a placeholder to use for the card art (*Michael Schweitzer* credits card).

**Comment by jleclanche** [comment]
I really want to keep copyrighted art to a minimum in the repo.

**Comment by beheh** [comment]
Merged as 111ac1dfcb17e43d5c09e3965bf6c83b0b3b94e8.

**Pull request closed without merging**
