### PR TITLE
Add loading screen

### PR DESCRIPTION
**Pull request by Epix37**
Based on #81.

- "Waiting for X..." messages are now logged, rather than displayed.
- I added a few random loading messages that came to mind. They are randomly picked from.
- There is probably a better way to do the html/css.
- Currently doesn't scale with app size - probably doesn't matter.
- Not amazing, but probably good enough for now. (at least better than "waiting for gamestate..." :))
  - Adding hero images might be nice - would require some preloading prioritization though.

https://cloud.githubusercontent.com/assets/7737910/14500565/eb5a9cbe-01a2-11e6-91e1-4fbd2c6bf5eb.gif

other way around: 
loadingscreen2

### CODE REVIEW

**Comment by beheh** [comment]
I really like the second version, nice and smooth transitions as well. Feedback from others? I can look into the scaling. We should also outsource the loading screen into a new component.

**Comment by jleclanche** [comment]
I prefer the clockwise one as well.

**Comment by Epix37** [comment]
Updated to spin clockwise.

**Comment by Epix37** [comment]
moved loading screen to it's own component

**Comment by beheh** [comment]
Replaced by #118, some of the code will be reused.

**Pull request closed without merging**
