### PR TITLE
Relicense to CC-BY-NC-SA 4.0

### LINKED ISSUE #62: Licensing is confusing.
The licensing of this project is confusing.

The README state:
````
Joust is licensed under the AGPLv3 for non-commercial uses exclusively. The full text of the license can be found in the LICENSE file.

Joust is not licensed for commercial use. Commercial exceptions can be granted on a case by case basis.
````

Yet referred LICENSE file is the AGPL-3.0 license text verbatim (I compared with the official version from the FSF) which doesn't put any restriction for the commercial use of software licensed under this license.

So which is it?

### PR DESCRIPTION
**Pull request by jleclanche**
Closes #62 

Need signoff from @beheh @andburn @Epix37

### CODE REVIEW

**Comment by Epix37** [comment]
:+1:

**Comment by andburn** [comment]
:+1:

**Comment by beheh** [comment]
:+1:
Let's revisit this at some point.

**Comment by jleclanche** [comment]
Landed in 2e0683358e9c7270dd4ae2ef42d185874aef63f0

**Pull request merged**
